name: finanzas_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.2

dependencies:
  crypto: ^3.0.7
  mysql_client: ^0.0.27
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  http: ^1.2.2
  lints: ^6.1.0
  test: ^1.25.6
